# Generated by Django 4.2.4 on 2023-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Women', 'Women'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='inform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
