# Generated by Django 4.2.4 on 2023-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_gender_account_inform'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone'),
        ),
    ]
