# Generated by Django 4.2.4 on 2023-08-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
