# Generated by Django 4.2.4 on 2023-08-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='publication',
            new_name='post',
        ),
    ]
